{{- if not .Values.daemon -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "exposecontroller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "exposecontroller.name" . }}
    helm.sh/chart: {{ include "exposecontroller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.Annotations | nindent 4 }}
  {{- else if .Values.Annotations }}
  annotations:
    {{- toYaml .Values.Annotations | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "exposecontroller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: exposecontroller
        image: "{{ .Values.image.repository }}:{{ default .Chart.Version .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /exposecontroller
        {{- if .Values.clean }}
        - --clean
        {{- end }}
        {{- range (coalesce .Values.args .Values.Args) }}
        - {{ . | quote }}
        {{- end }}
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ include "exposecontroller.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}