{{- $cluster := not (kindIs "invalid" .Values.watchNamespaces) -}}
{{- if kindIs "invalid" .Values.watchCurrentNamespace -}}
{{- else if and $cluster .Values.watchCurrentNamespace -}}
  {{- fail "Must either watch the current namespace or specific namespaces" -}}
{{- else -}}
  {{- $cluster = not .Values.watchCurrentNamespace -}}
{{- end -}}

{{- if $cluster -}}
kind: ClusterRole
{{- else -}}
kind: Role
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "exposecontroller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "exposecontroller.name" . }}
    helm.sh/chart: {{ include "exposecontroller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "update"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
{{- if $cluster }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "exposecontroller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "exposecontroller.name" . }}
    helm.sh/chart: {{ include "exposecontroller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  kind: ClusterRole
  name: {{ include "exposecontroller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "exposecontroller.fullname" . }}
{{- if $cluster }}
    namespace: {{ .Release.Namespace }}
{{- end }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "exposecontroller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "exposecontroller.name" . }}
    helm.sh/chart: {{ include "exposecontroller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
