{{- if .Values.endpoints.create }}
{{- $ips := .Values.glusterfs.server }}
{{- if eq .Release.Name "testRelease" "test-release" }}
  {{- $ips = list "test" }}
{{- else if not .Values.glusterfs.server }}
  {{- fail "no glusterfs server provided" }}
{{- else if kindIs "string" .Values.glusterfs.server }}
  {{- $ips = split "," .Values.glusterfs.server }}
{{- else if eq 0 (len .Values.glusterfs.server) }}
  {{- fail "no glusterfs server provided" }}
{{- end }}
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ template "glusterfs-client-provisioner.endpointsName" . }}
  labels:
    app: {{ template "glusterfs-client-provisioner.name" . }}
    chart: {{ template "glusterfs-client-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subsets:
{{- range $i, $ip := $ips }}
- addresses:
  - ip: {{ $ip | quote }}
  ports:
  - port: 1
{{- end }}
{{- if .Values.endpoints.createService }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "glusterfs-client-provisioner.endpointsName" . }}
  labels:
    app: {{ template "glusterfs-client-provisioner.name" . }}
    chart: {{ template "glusterfs-client-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports: []
  clusterIP: None
  type: ClusterIP
{{- end }}
{{- end }}
