{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "glusterfs-client-provisioner.serviceAccountName" . }}
  labels:
    app: {{ template "glusterfs-client-provisioner.name" . }}
    chart: {{ template "glusterfs-client-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "glusterfs-client-provisioner.fullname" . }}-runner
  labels:
    app: {{ template "glusterfs-client-provisioner.name" . }}
    chart: {{ template "glusterfs-client-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
{{- if .Values.podSecurityPolicy.enabled }}
  - apiGroups:      ['extensions']
    resources:      ['podsecuritypolicies']
    verbs:          ['use']
    resourceNames:  [{{ template "glusterfs-client-provisioner.fullname" . }}]
{{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "glusterfs-client-provisioner.fullname" . }}-runner
  labels:
    app: {{ template "glusterfs-client-provisioner.name" . }}
    chart: {{ template "glusterfs-client-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ template "glusterfs-client-provisioner.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "glusterfs-client-provisioner.fullname" . }}-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "glusterfs-client-provisioner.fullname" . }}-leader-locking
  labels:
    app: {{ template "glusterfs-client-provisioner.name" . }}
    chart: {{ template "glusterfs-client-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
{{- if .Values.podSecurityPolicy.enabled }}
  - apiGroups:      ['extensions']
    resources:      ['podsecuritypolicies']
    verbs:          ['use']
    resourceNames:  [{{ template "glusterfs-client-provisioner.fullname" . }}]
{{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "glusterfs-client-provisioner.fullname" . }}-leader-locking
  labels:
    app: {{ template "glusterfs-client-provisioner.name" . }}
    chart: {{ template "glusterfs-client-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ template "glusterfs-client-provisioner.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "glusterfs-client-provisioner.fullname" . }}-leader-locking
  apiGroup: rbac.authorization.k8s.io
{{- end }}