# Default values for exposecontroller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: olliai/exposecontroller
  tag:
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
timeout: null
resyncPeriod: null
daemon: false
watchNamespaces: null

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

Annotations: {}
Args: []

nodeSelector: {}

tolerations: []

affinity: {}
