name: Release Charts

on:
  push:
    branches:
      - master
  schedule:
    # run this pipeline every day
    - cron:  '0 10 * * *'
  repository_dispatch:
    types: updateCharts

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Execute script to get charts from upstream repos
      - name: Prepare Charts
        run: >
          git reset --hard origin/master &&
          git checkout master &&
          git pull &&
          bash ./scripts/build-charts.sh $(pwd)/charts $(pwd)/conf.d/upstream_charts.json
      # Push new charts back to repo
      - name: Push Charts
        env:
          RELEASE_USER_TOKEN: ${{ secrets.RELEASE_USER_TOKEN }}
          RELEASE_USER: ${{ secrets.RELEASE_USER }}
          RELEASE_USER_NAME: ${{ secrets.RELEASE_USER_NAME }}
          RELEASE_USER_EMAIL: ${{ secrets.RELEASE_USER_EMAIL }}
        run: >
          git config --global user.name "${RELEASE_USER_NAME}" &&
          git config --global user.email "${RELEASE_USER_EMAIL}" &&
          git remote add publisher https://${RELEASE_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY} &&
          git add -A &&
          (git commit -m "Automated publish: $(date -u) ${GITHUB_SHA}" || exit 0) &&
          git pull --rebase publisher master &&
          git push publisher master
      # Update gh-pages
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.RELEASE_USER_TOKEN }}
